apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-burst: '5'
    nginx.ingress.kubernetes.io/limit-rps: '10'
    nginx.ingress.kubernetes.io/real-ip-header: X-Forwarded-For
    nginx.ingress.kubernetes.io/set-real-ip-from: 0.0.0.0/0
  name: frontend-ingress
  namespace: presentation
  labels:
    tier: presentation
    ingress-type: public-web
spec:
  ingressClassName: nginx
  rules:
  - host: runpath.duckdns.org
    http:
      paths:
      - backend:
          service:
            name: frontend-deployment-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - runpath.duckdns.org
    secretName: frontend-tls
