apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod","kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/limit-burst":"5","nginx.ingress.kubernetes.io/limit-rps":"10","nginx.ingress.kubernetes.io/real-ip-header":"X-Forwarded-For","nginx.ingress.kubernetes.io/set-real-ip-from":"0.0.0.0/0"},"name":"frontend-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"runpath.duckdns.org","http":{"paths":[{"backend":{"service":{"name":"frontend-deployment-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["runpath.duckdns.org"],"secretName":"frontend-tls"}]}}
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/limit-burst: "5"
      nginx.ingress.kubernetes.io/limit-rps: "10"
      nginx.ingress.kubernetes.io/real-ip-header: X-Forwarded-For
      nginx.ingress.kubernetes.io/set-real-ip-from: 0.0.0.0/0
    creationTimestamp: "2025-12-05T17:46:02Z"
    generation: 4
    name: frontend-ingress
    namespace: default
    resourceVersion: "1765079589924351024"
    uid: 7cd19b7a-80c5-468d-b4c1-12c9b85b9f8f
  spec:
    ingressClassName: nginx
    rules:
    - host: runpath.duckdns.org
      http:
        paths:
        - backend:
            service:
              name: frontend-deployment-service
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - runpath.duckdns.org
      secretName: frontend-tls
  status:
    loadBalancer:
      ingress:
      - ip: 136.114.109.33
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod","kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/proxy-set-headers":"default/mobile-proxy-headers"},"name":"mobile-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"mobile.runpath.duckdns.org","http":{"paths":[{"backend":{"service":{"name":"api-gateway-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["mobile.runpath.duckdns.org"],"secretName":"mobile-tls"}]}}
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-set-headers: default/mobile-proxy-headers
    creationTimestamp: "2025-12-06T23:29:52Z"
    generation: 2
    name: mobile-ingress
    namespace: default
    resourceVersion: "1765079589920783009"
    uid: 5ccf9a8f-c3b0-4301-abe7-8cca837cd4f2
  spec:
    ingressClassName: nginx
    rules:
    - host: mobile.runpath.duckdns.org
      http:
        paths:
        - backend:
            service:
              name: api-gateway-service
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - mobile.runpath.duckdns.org
      secretName: mobile-tls
  status:
    loadBalancer:
      ingress:
      - ip: 136.114.109.33
kind: List
metadata:
  resourceVersion: ""
