apiVersion: v1
data:
  API_GATEWAY: http://api-gateway-service.orchestration.svc.cluster.local:80
  AUTH_SERVICE: authApi/graphql
  DISTANCE_SERVICE: distanceApi
  NEXT_PUBLIC_MAPBOX_TOKEN: '''pk.eyJ1Ijoic3ZhcGUyMTMiLCJhIjoiY204YzhsMmR0MW40cDJxcTFveXAyYmppMyJ9.erDPDm9SwAigpSj6FURroA'''
  PORT: '3001'
  ROUTES_SERVICE: routesApi/routes
kind: ConfigMap
metadata:
  labels:
    app: frontend-deployment
    tier: presentation
    app.kubernetes.io/managed-by: cloud-console
  name: frontend-deployment-config-yftt
  namespace: presentation
