apiVersion: v1
data:
  Host: $host
  X-Client-Type: mobile
  X-Forwarded-For: $proxy_add_x_forwarded_for
  X-Forwarded-Proto: https
  X-Real-IP: $remote_addr
kind: ConfigMap
metadata:
  name: mobile-proxy-headers
  namespace: default
