apiVersion: v1
data:
  AUTH_SERVICE_ENDPOINT: http://api-gateway-service.orchestration.svc.cluster.local:80/authApi/graphql
  SPRING_MAIL_PASSWORD: TBD
  SPRING_MAIL_USERNAME: TBD
  SPRING_RABBITMQ_HOST: rabbitmq.backend.svc.cluster.local
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_RABBITMQ_PORT: '5672'
  SPRING_RABBITMQ_USERNAME: guest
kind: ConfigMap
metadata:
  labels:
    app: notification-deployment
    tier: backend
    app.kubernetes.io/managed-by: cloud-console
  name: notification-deployment-config-b2am
  namespace: backend
