apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-deployment
    tier: presentation
  name: frontend-deployment-service
  namespace: presentation
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: frontend-deployment
    app.kubernetes.io/managed-by: cloud-console
  sessionAffinity: None
  type: ClusterIP
